CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name TEXT NOT NULL CHECK (name <> ''),
lastname TEXT NOT NULL CHECK (lastname <> ''),
email TEXT NOT NULL,
password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
id SERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name TEXT NOT NULL CHECK (NAME <> ''),
description TEXT,
done BOOLEAN,
deliverydate DATE NOT NULL,
userid INTEGER REFERENCES users(id)
);

INSERT INTO tasks(name, description, done, deliverydate, userid)
VALUES('task', 'to be done', false, '2021-12-12', 9);